### PR TITLE
Add an 'alltext' field to the ES mappings in registry.py

### PR DESCRIPTION
**Pull request by romseygeek**

### CODE REVIEW

**Comment by JorgeMartinezG** [comment]
Hi, it seems an elasticsearch problem related to delete an index that has not been created. I replicated the issue and saw this in Es logs.
image

Changing the type "text" to "string" solved the issue. Please review @romseygeek

**Comment by romseygeek** [comment]
Ah, this will be because I was developing against ES 5.0.0 and travis is testing against ES 1.7.

**Comment by ingenieroariel** [comment]
I'll think about our options to keep targeting the version we have on our
client networks but still be able to prepare for features coming in 5.0.

**Comment by ingenieroariel** [comment]
Master is now testing against Elasticsearch 5.0 and 1.7 - can you make a new commit to have travis re-run?

**Pull request merged**
