### PR TITLE
Add multi-field search with boosts

### PR DESCRIPTION
**Pull request by sstults**

### CODE REVIEW

**Comment by sstults** [comment]
I'm looking into why this is failing on ES_VERSION < 2

**Comment by ingenieroariel** [comment]
Hey Scott,

In Elasticsearch 1.7 the tests are failing. It seems to be related with the ordering of the results, could you help us investigate? It should be as easy as changing the elasticsearch version in docker-compose.

**Comment by sstults** [comment]
For ES < 2 the full-text query was being added to the boolean query filter. It needs to be outside of the filter in order to preserve score, and score is what lets field boosts work. So I reordered the final structure of the query a bit.

**Comment by JorgeMartinezG** [comment]
@sstults It means that for versions > 2, elasticsearch computes scores even the query_string is within a filter? Good to know!

**Pull request merged**
